### ISSUE TITLE
Spend Backpressure

### ISSUE THREAD

**Issue by matdehaast** [adrianhopebailie/open-payments#12]
Ability to notify incoming spends as coming in too fast. Maybe s `429` error code?

**Comment by sharafian** [comment]
we should also specify what the recommended behavior is for the site implementing this. should they retry? error? can we give some general guidance on what rate limit wallets should support for their users, and should they let some high-throughput users upgrade their accounts for higher rate limits?

**Comment by kincaidoneil** [comment]
This seems kinda complicated. Alternatively, would a webhook/callback for every incoming payment for a session work better?

- The merchant wouldn't need to poll for incoming payments (e.g. this doesn't seem as practical for streaming payments)
- Merchant has flexibility to perform the accounting within their own system (might be not be a huge deal since some degree of integration work is necessary for this anyways)

---

One interesting way to model this: the merchant's backend API could effectively be a settlement engine. (Hang tight, don't lose me!). Each session would be a unique account on the connector hosted by the merchant's wallet provider; the settlement engine associated with each of those accounts is just operated by the merchant. When the remote STREAM receiver for a session receives money, it'd notify the merchant that it received the money using the `/accounts/:id/settlements` endpoint. The merchant could even set the frequency of these notifications by configuring settle thresholds.

Of course, the settlement engine isn't performing any traditional settlement per se, it's just accounting, for this account associated with session `abc`, now I have to serve them with `$x` worth of content (which _is_ a settlement, in a sense!).

**Comment by adrianhopebailie** [comment]
@kincaidoneil I think the idea of using the Settlement Engine API as the way of doing aggregation of a STREAM is super-cool 👍 

However, I think a website-initiated API (i.e. the website polling the wallet, as opposed to a web-hook called by the wallet) is more appropriate to the use case because the scenario is that the website is currently servicing request(s) and is proactively going out to the wallet to notify it of consumption by the user AND to check the balance on the current session.

Note that the purpose of this API is a "service" to websites that don't want to track this themselves. It's quite possible that some wallets might not support the "spend" API.

ITO recommendations, I think sites should only call this when they need to record that a user has consumed some content/service so it should be unlikely that they hit rate limits.

I think standard HTTP API behaviour makes sense as @matdehaast suggests:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

**Comment by kincaidoneil** [comment]
> the scenario is that the website is currently servicing request(s) and is proactively going out to the wallet to notify it of consumption by the user AND to check the balance on the current session

How does the website know when the payment is complete? Would it keep retrying spends against the wallet when it asks too early?

> ITO recommendations, I think sites should only call this when they need to record that a user has consumed some content/service so it should be unlikely that they hit rate limits.

Are you envisioning the website serves the content before actually issuing the spend?
