### ISSUE TITLE
Associate payment to a WM Provider

### ISSUE THREAD

**Issue by sharafian** [adrianhopebailie/open-payments#17]
# Background

We've been thinking about the idea of looking at payments on a per-provider rather than per-user basis for the purposes of serving web-monetized exclusive content. Basically instead of making sure that we made enough money off of a given visitor, a site would check if they made enough money off of a visitor's WM provider before serving exclusive content. If a user runs their own provider then this system is equivalent to the current per-user accounting.

This has a few advantages. One is that a site can start serving WM content faster, without waiting for SPSP to intialize. The site can just see the user's provider and let them in right away once they validate the provider has paid. Another advantage is that this smooths out users with varying rates on a single provider.

# Proposed Changes

- Add a `Web-Monetization-Provider` header to SPSP queries. This includes a JWT or other signed authorization issued by the provider which can be verified by the site (the method of auth would be standardized so the site doesn't need to be aware provider-by-provider. public key would be hosted on well known URL). This lets wallets associate sessions to providers.

- Add a `"provider"` field or something similar (more generic) to the session API response. Then the site can account for sessions based on which provider they're from and pool them. If the wallet had a mechanism for automatically pooling sessions based on the provider it would also solve this problem and may be more convenient for the site.

- Add a way for the site to be notified of incoming funds. If the site is pooling by provider in its own systems then this means they don't need visitor to notify them every time they pay and then query the session and save it to their systems (which could be unreliable and requires unnecessary client-server communication). They could just get the wallet to tell them all the incoming funds in connection with their provider. This would have to be reasonably quick (~1s) so that the first visitor can access content and so that users running their own provider have a good experience. This is not necessary if a site can query by provider on the wallet directly.

CC @wilsonianb @adrianhopebailie @matdehaast

**Comment by adrianhopebailie** [comment]
@matdehaast and I have been talking through some ideas for this and we have a clarifying question.

How sensitive is the identifier of the provider?

In other words, if a user were to spoof their provider is that an issue? In the simplest case one can imagine there being multiple providers each with different special arrangements with different publishers.

If user's had knowledge of those arrangements it would be very easy to simply pretend to be using a particular provider when visiting sites that are known to provide extra value when that's the case.

The best way to solve this is some signed attestation.

But then the question is, how does that get to the extension OR must it always be sent from the provider's servers?

If it is sent by the extension it has to be very short-lived which likely means a new attestation per session, i.e. an extra round trip between the extension and the provider's servers each session.

If it is sent from the provider's servers then we have to worry about privacy. How much info is sent to the provider's servers in order to send the attestation? It needs to be enough so the website can correlate the attestation with the session but not enough that the provider can figure out the website.

## Proposal

What if we moved the STREAM sender to the provider's servers? It dramatically simplifies the extension AND makes this easier to implement using payment handlers.

The flow would be something like:

  1. The extension parses a PP (`$wallet.example/alice`) and determines the session endpoint to be `https://wallet.example/sessions`. 
  2. The extensions creates a session by doing a POST to that endpoint (it COULD provide a provider ID already, which is a hint that this session will be paid by a specific provider. This allows the wallet to prefetch public keys etc if necessary)
  3. The extension calls the provider servers telling the provider to pay the session (identified by the session URL).
  4. The provider does a GET on the session (`https://wallet.example/sessions/c59e26ed-dd92-4946-85dc-015791d44d4d`) but provides a signed attestation of it's identity as an `Authorization` header. The session details are returned including the ILP Address and Secret but the `subject` of the session (the payment pointer of the website) is NOT included.

```http
HTTP/1.1 200 Success
Content-Type: application/json

{
  "name": "//wallet.example/sessions/0f09dc92-84ad-401b-a7c9-441bc6173f4e",
  "destination": "g.example.42e0f0c9284ad401b7c941bc6173f4e",
  "shared_secret": "AvLaEGc+ojGHVezQF9DC4/7F5YIvrNPx/VM+4hJkCbs=",
  "asset": {
    "code": "USD",
    "scale": 6
  },
  "expire_time": "2019-12-12T00:56:00.123Z"
}
```

  5. One of:
    a. the provider starts a paying the website until it gets a request from the extension to stop OR it times out waiting for the extension to tell it to continue.
    b. the provider returns the STREAM credentials to the extension which starts paying.

Co-incidentally this pattern (submitting the URL of a session/invoice to pay) to the wallet is one we've been exploring more generally for checkout and other use cases.

It's a very elegant way to do pull-payments (delegated push) for example.

 1. Merchant creates mandate at user's wallet
 2. Merchant creates invoice on their own wallet
 3. Merchant submits invoice URL to user's wallet to pay (backed by mandate).

**Comment by wilsonianb** [comment]
@adrianhopebailie 
I think the provider authenticating with the website is more important than authenticating with the wallet. Your proposal does result in the website authenticating the provider (via the wallet), but I think the roundabout approach misses out on the potential benefit of:
>a site can start serving WM content faster, without waiting for SPSP to intialize. The site can just see the user's provider and let them in right away once they validate the provider has paid.

(It actually might not be a problem to spoof the provider at the wallet session, which would result in any actual paid amounts to be credited to pooled balance of the provider you're pretending to a user of.)

**Comment by adrianhopebailie** [comment]
> I think the provider authenticating with the website is more important than authenticating with the wallet.

I'm still not sure how it does that in an un-spoofable way? Anything the provider sends to the extension can be replayed so a signed assertion has to come directly from the provider's servers.

**Comment by sharafian** [comment]
> How sensitive is the identifier of the provider?
>
> In other words, if a user were to spoof their provider is that an issue? In the simplest case one can imagine there being multiple providers each with different special arrangements with different publishers.

We should make it unforgeable, because it's going to be used to determine average rate per provider / how much is available to users of that provider. People who don't belong to the provider should not be allowed to authenticate as such.

> The best way to solve this is some signed attestation.

Agreed, I think we discussed JWT or similar.

> But then the question is, how does that get to the extension OR must it always be sent from the provider's servers?

The extension could pull many attestations at once from the provider's servers, and store them locally. When it needs more it refreshes them. Right now the provider never talks to the site directly.

> If it is sent by the extension it has to be very short-lived which likely means a new attestation per session, i.e. an extra round trip between the extension and the provider's servers each session.

I think we'd want to pre-fetch and cache many. Although depending on their expiry it may be easier to fetch them with the BTP token which is already requested for every page session. So it's not really adding round trips in any case.

> If it is sent from the provider's servers then we have to worry about privacy. How much info is sent to the provider's servers in order to send the attestation? It needs to be enough so the website can correlate the attestation with the session but not enough that the provider can figure out the website.

Agreed, I don't like involving the provider into the flow any more than we have to.

> What if we moved the STREAM sender to the provider's servers? It dramatically simplifies the extension AND makes this easier to implement using payment handlers.

This just introduces the privacy issues which you just brought up, though. The provider's servers would learn every payment pointer you're paying to, which is unacceptable. We could come up with schemes that shield the user's identity from the provider when they pay to a site, but it's still leaking more information than we have to.

**Comment by wilsonianb** [comment]
I think this would get us unforgeable/unreplayable provider verification:

1. Extension generates a public private key pair.
2. Extension asks WM provider to include that public key in the attestation JWT(s), endorsing the extension's public key.
3. Whenever the user visits a site, the extension creates a second JWT containing the site's payment pointer (and the wm id?) signed by its own private key.
4. The extension sends both JWTs as well as the WM provider's public key (so the website never has to query the wm provider) to the website.

I'm not sure how best to handle the WM provider rotating its key. Perhaps the public key itself would suffice as the provider id, with the downside of its pooled balances basically resetting whenever there's a key change?

In order for the website to serve gated content prior to (or without) receiving payment in the session, would the extension set the JWTs and public key as properties on `document.monetization`?

On the topic of changing the web monetization spec, I feel like the unverified amounts in `monetizationprogress` events aren't that useful. What if the receiver wallet signed and sent tokens with fulfilled packet amounts via STREAM to the extension? It could then include those verifiable amounts in the `monetizationprogress` events. This could give us a near term wm payment verification solution in which wallets just need to add the tokens, while also giving us more time to finalize the OPay spec.

**Comment by adrianhopebailie** [comment]
> This just introduces the privacy issues which you just brought up, though.

I think if you follow the flow in the proposal it doesn't reveal anything more than who the receiving wallet is (which the provider needs to know for compliance anyway right?).

**Comment by adrianhopebailie** [comment]
@wilsonianb a key chain is definitely worth exploring further.

I think hosting the provider public keys using the standard OAuth meta-data mechanisms will work fine. No need to send them around.

**Comment by sharafian** [comment]
> I think if you follow the flow in the proposal it doesn't reveal anything more than who the receiving wallet is (which the provider needs to know for compliance anyway right?).

Apologies, misread that. I still am not sure if it'll be an improvement or not because it requires lots of messages back and forth. It also means the backend can no longer be stateless. There's a chance it'll make the system more error prone and more complicated to reason about. But the good thing is that flow doesn't need to be decided by this spec; from the wallet's side it doesn't matter.

>  @wilsonianb a key chain is definitely worth exploring further.

Problem with a keychain is that this creates an identifier of the user that exists on every WM site they visit and can be used to track them. There may be some fancy crypto that could be used to authorize many keys without linking them to one another, but if the extension is just presenting its public key to everyone it doesn't work from a privacy perspective

**Comment by wilsonianb** [comment]
Could the wm provider instead issue everyone the same temporary signing key and endorsement token (which would include a short-ish expiration)?

**Comment by sharafian** [comment]
That could work, but if you give the user the ability to generate tokens then they can also "share" their provider with other people and it would be hard to detect. They could even resell that access to the detriment of the provider because the people with their re-sold tokens would be drawing from the same pool as the provider's actual members. Whereas if the tokens were fetched from the provider's API then it would be easy to detect when someone had been re-selling access. They would have a very large spike in the number of tokens being requested and they could be kicked off the provider

**Comment by wilsonianb** [comment]
I'm imagining the extension fetching the token and key from the provider's API. The token (and key) would expire in something like an hour.
Every user's extension would get the same token and key from the provider each hour.

It seems like there'd be at least three ways to unfairly draw from provider's pool:
- individual user with extremely heavy usage
- sharing or selling login (could potentially be detected by provider API)
- repeatedly distribute the tokens and keys (requires higher technical effort)
