### ISSUE TITLE
Wallet balance tracking for Website

### ISSUE THREAD

**Issue by matdehaast** [adrianhopebailie/open-payments#6]
@wilsonianb suggested having the ability for the Website to make requests against an invoice to consume the balance.

Essentially the website would make a PUT/POST request against the invoice 

```
POST https://wallet.example/invoices/4309dc23-12ad-401c-3ec9-551bc61765ab7/transaction HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "amount": "100",
}
```

This would result in either a `201` if there is enough available balance on the invoice or a `402` if there was not enough available balance on the invoice. I would suggest that the wallet tracks this as another balance item on the invoice. 

The reason this is a nice approach to take is that essentially it leaves balance tracking logic to the wallets and not the websites/applications and thus removes complexity.

**Comment by adrianhopebailie** [comment]
I had a read through the Slack thread here: https://interledger.slack.com/archives/CPL2HTF54/p1572020365082200

My one concern is that the wallet and the website are tracking different things. 
 - the wallet is tracking the money paid to the receiver from the user,  and 
 - the website is tracking the consumed value of some service it is delivering to the user.

I can see how getting the wallet to track this for the website helps the website but I'm not sure why it's of any value to the wallet. (It just adds complexity to the implementation)

An alternative:

Instead of doing a PUT/POST to the wallet for an amount to "consume" the website simply tracks the consumed amount. When it wants to check if the user has exceeded their prepaid quota it does a GET on the invoice to ensure the balance is higher than the sum of the consumed amounts.

This is the same number of roundtrip interactions and the website has the flexibility to aggregate multiple invoices for a user etc.

**Comment by wilsonianb** [comment]
>I can see how getting the wallet to track this for the website helps the website but I'm not sure why it's of any value to the wallet. (It just adds complexity to the implementation)

Hard to argue with that.

For the proposed alternative, the website could track both the balance and consumed amount. Since it should be safe to assume that the balance can only increase, the service would only need to check the latest invoice balance at the wallet whenever the new consumed amount would exceed the locally stored balance.

I've been looking into how websites could do payment verification at their backend's ingress/proxy/loadbalancer instead of the backend service itself. I think it could work well for this balance tracking to happen in an "external" authorization service. The routing configuration could then use something like this [Envoy filter](https://www.envoyproxy.io/docs/envoy/v1.12.0/configuration/http/http_filters/ext_authz_filter) to check for payment before handling certain requests.

**Comment by sharafian** [comment]
> Instead of doing a PUT/POST to the wallet for an amount to "consume" the website simply tracks the consumed amount. When it wants to check if the user has exceeded their prepaid quota it does a GET on the invoice to ensure the balance is higher than the sum of the consumed amounts.

Tracking consumed amount on the wallet side saves a lot of headache on synchronizing state between the wallet and the site backend. When you have invoices that can expire and you're also expiring consumed amounts on the site backend it's a big footgun. if the site expires consumed amount and the wallet unexpectedly extends the expiry for the received amount it could lead to a user getting more than what they paid for.

Putting all the invoice state on the wallet gives a lot of flexibility to site developers and it also shouldn't be terribly hard from the wallet side because they already have to update the invoice on lots of rapid events

**Comment by adrianhopebailie** [comment]
> Tracking consumed amount on the wallet side saves a lot of headache on synchronising state between the wallet and the site backend.

But it's not the wallet's responsibility to track consumption of a service hosted by someone else. 

E.g. If I use PayPal to collect payments from my customers then PayPal tracks the amount of money they have paid me. If those payments are used to buy "credits" for consuming some service then PayPal won't track the purchase of the credits or the consumption of the credits.

In this use case, is the user a customer of the website or the content provider?
i.e. Is the user's prepaid credit with the website or with the content provider (who owns the wallet account)?

If it's with the website then I really don't think it makes sense for the content provider's wallet to track these balances.

**Comment by sharafian** [comment]
I think "what makes sense" from a conceptual elegance standpoint is less important than practical concerns around usability.

Paypal has a well-defined interface between paypal's systems and the systems of a site that integrates paypal. Any transaction that paypal notifies the site of can be looked up forever. They define the specific ways it can change, how they notify that, and so on.

Our interface is a little bit more complicated because of the optimizations that have to be done to prevent from storing every invoice indefinitely. We need to find some way to pin down that interface between the wallet and the site backend that wants to check invoices on the wallet.

We could make our interface more well-defined by pinning down the way that an expiry works, when that changes, etc. Then all of that logic also needs to be mirrored on any site backend that wants to keep track of invoices.

Alternatively, and what I think would be easier, is to introduce an interface that allows you to do this common operation of "consuming" an invoice on the wallet side. That makes the ask much smaller for the sites that want to use this invoice functionality. Making this as easy as possible for websites to integrate should be important to us

**Comment by wilsonianb** [comment]
>We could make our interface more well-defined by pinning down the way that an expiry works, when that changes, etc. 

I'm trying to think of how we can do that given this (from https://github.com/interledger/rfcs/issues/563)

>In the Web Monetization use case this would involve the sender making a new call to the Payment Pointer URL using the same requestId as before. This should return new credentials but the server should continue to associate incoming payments on the new connection with the same requestId.

Unless the wallet is able to forget the balance for a particular requestId/invoice (by deleting the invoice), I don't think it would ever be safe for a website backend to stop tracking the amount used for an invoice.

Would it be ok for a wallet at a time of its choosing (at or after the `expire-time`?) to expire STREAM credentials and delete the invoice? If the sender then made a new call to the Payment Pointer URL using the same id, the wallet would recreate the invoice but with the balance reset to 0.

A website backend could then know it's safe to stop tracking an invoice (and its amount used) whenever the wallet returns 404 for that invoice. To handle the recreated invoice scenario, the invoice could include `created_at` which the website backend would store along with the id, balance, and amount used (and `expire-time`?). If the website backend sees a different `created_at`, it would accept the potentially lower balance AND reset the amount used according the previous values. For example, if the previously seen balance was 10 and amount used was 8, then the amount used would be reset to -2. (The sender wouldn't benefit from this credit if the website backend stops tracking the invoice after getting 404 before the invoice is recreated.)

The scenario of a payment happening and the wallet deleting the invoice before the website backend ever sees the balance change (potentially to the detriment of a sender) seems like an issue whether it's the wallet or website backend tracking the amount used.

**Comment by sharafian** [comment]
> A website backend could then know it's safe to stop tracking an invoice (and its amount used) whenever the wallet returns 404 for that invoice

That's a good idea, if the wallet could guarantee that a balance will never be preserved between 404s then it could set an expiry, check and get the 404 and delete or schedule another check at the new expiry if it is not expired. This would be a very noisy approach that involves a lot of checks but it would be somewhat safe at least

I think the best would still be allowing the wallet to track the amount consumed out of an invoice.

Talking with @wilsonianb we did discuss whether changing the name from "invoice" to something else could make this feature more understandable. Maybe something like  "sub-balance" or "voucher" where it represents money that you're basically pre-paying to the wallet for a future service. It would make sense that a "voucher" object would track the amount that has been consumed.

**Comment by wilsonianb** [comment]
>Talking with @wilsonianb we did discuss whether changing the name from "invoice" to something else could make this feature more understandable. 

I was originally just thinking of an alternative name since invoices usually involve a specific owed amount / outstanding balance which doesn't seem to be the case here.

If we instead called it a subaccount or segregated balance or voucher, it could make sense for its balance to not be credited anywhere else. So determining the amount a user holds at a wallet would involve tallying the balance in all subaccounts.

Then payment verification is possible by successfully transferring the consumed amount from the subaccount to the primary/root(?) account. This could happen with either a transfer function or creating an invoice (with an amount owed along the lines of the current [SPSP Invoices](https://interledger.org/rfcs/0037-spsp-invoices/)) addressed to the subaccount which would be automatically satisfied assuming the balance was sufficient (<-- might be overly complicated).

**Comment by adrianhopebailie** [comment]
_I wrote this yesterday but forgot to send 🤦‍♂_  

> I think "what makes sense" from a conceptual elegance standpoint is less important than practical concerns around usability.

I don't agree with this entirely. If we decide that it's worthwhile for wallets to provide this "consumption tracking" service to websites that's fine but I don't want to confuse users by simply tacking on a way to "reduce an invoice". That is a concept that is certain to cause confusion.

As @wilsonianb points out, there are some complex relationships here we need to be clear on first so we get the accounting right. Then let's define how to achieve the desired use case.

Let's assume the following:
 - Alice uses XYZ Website and is streaming money to Bob (the content provider)
 - XYZ Website tracks the money paid by Alice to Bob
 - XYZ Website gives Alice access to Bob's content but only if Alice has sent enough money to Bob

A few questions:
 
 1. Does Bob always get all the money? i.e. If Alice sends $10 to Bob but only consumes $8 worth of content does Bob still get $10?
 2. Assuming yes, what happens to the remaining $2 credit?
 3. Can Alice still spend that $2 on other content at XYZ?
 4. What if Alice starts a new session but is still consuming Bob's content?

I'm assuming the answers are: Yes, Alice has lost it, No, Still No

In that case it feels like we need to distinguish between the invoice (which the wallet uses to track money coming in for Bob) and the session (which the website uses to track Alice's credit).

Alice gets additional credit in her session each time she sends money to Bob. She consumes credit when she consumes content.

In effect, each time Alice visits the website she is buying a new session.

So perhaps we need the ability for a website to request that a wallet track "sessions" and somehow tie these to an invoice?

_Added this morning after reading last two comments from @wilsonianb and @sharafian:_

The idea of a sub-account is good but I think it needs to be tracked distinctly from the invoice.

The balance on the invoice can only go up, that's money earned by Bob.
The balance on the sub-account can go up or down, that's credit paid for and consumed by Alice.

That still leaves the question of what happens to the sub-account when the session ends. Does the remaining balance get transferred to the website and the account closed? (i.e. How does the accounting work)

**Comment by adrianhopebailie** [comment]
@matdehaast and I dug into this this morning, and here's our suggestions based on what has been discussed so far:

 - Lets distinguish between an "invoice" which has a fixed amount, known ahead of time, and a "session account" an ephemeral sub-account that is simply used to track payments during a session.
 - For WM the user creates a "session account" (not an invoice) and starts paying into this.
 - Wallets can provide "SPEND" permission to third-parties on a user's session accounts which reduces the balance of that account.
 - When money is spent from a session-account it simply moves from that account into the user's main account (or some other account).
 - When the session account expires any remaining balance moves into the user's main account.

This allows wallets to provide nice aggregation of incoming money to their users. They can either give users a full breakdown of all sessions or aggregate them based on time or some other dimension.
E.g. Every 5 minutes all expired sessions can be credited to the user's account.

I'll make a PR to the explainer quick to add this concept
